version: "3"
services:
  genericbot:
    build: .
    container_name: genericbot
    env_file: .env
  mongodb:
    # mongodb 5 seems to not run on debian 10
    #image: mongo:5.0.0-focal
    image: mongo:4.4.7-focal
    container_name: mongodb
    command: "mongod --bind_ip 0.0.0.0"
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
      - ./devdump.tar:/tmp/db.tar

volumes:
  mongodb:
